/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
import java.util.ArrayList;
import java.util.HashSet;


public class Solution {

   public static void main(String[] args) {
    	 ArrayList<Long> fibs = new ArrayList<Long>();
    	 long sum =0;
        long max = 4000000;
        long a = 1, b = 1, c;
        fibs.add(0l);
        fibs.add(1l);
        do{
            c = a+b;
            fibs.add(c);
            a = b;
            b = c;
        }while(c <= max);
        for(int i=1;i<fibs.size();i++){
        	if(fibs.get(i) % 2 == 0){
        		sum = sum + fibs.get(i);
        	}
        }
        System.out.println(sum);
    }
    
}
